<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-JuicePositiveRespon</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>01e16b84-30ec-497f-841b-cdecbe0d05e6</testSuiteGuid>
   <testCaseLink>
      <guid>bf808943-b6d3-4ce9-9758-94965e5e7a4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Website/TC-Registration/TC-Registrasionn Success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dd2e65e0-f95d-4b66-beab-3c541e9b5c4c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/katalon data/register_success</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dd2e65e0-f95d-4b66-beab-3c541e9b5c4c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>47279896-9c6f-4f04-b4c9-2bf911490c5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd2e65e0-f95d-4b66-beab-3c541e9b5c4c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b559f82c-ab84-436a-82bb-ce73c158a0bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d734ba28-5194-485b-800f-1c0f037cb3b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e39141b0-788c-4de1-8483-50a32cdca02d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa7e1a9d-437b-4947-be3d-e690413e9a30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Website/TC-Login/TC-LoginSuccess</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>273d84ab-b89b-4fcd-bb2d-afb9ab9b11aa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/katalon data/login_valid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>273d84ab-b89b-4fcd-bb2d-afb9ab9b11aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>30efbb04-c531-463c-8d40-1209354596f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>273d84ab-b89b-4fcd-bb2d-afb9ab9b11aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fceb57b2-bc0d-428c-903d-b4ba3f34e186</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>397bf90f-0673-4be2-8d7a-6475e5124b87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5393792-bb91-4b4b-af21-ddc58b2df8c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5cb4dff-1b06-47b1-9aee-ec8009a9eecf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Website/Blok/CloseBrowser</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
